### ISSUE TITLE
svd_fix

### ISSUE THREAD

**Issue by SunYanCN** [KhrulkovV/tt-pytorch#1]
[root@gpu-4 sentiment]# mkdir logdir
[root@gpu-4 sentiment]# python train.py --gpu=0 --embed_dim=256 --dataset=imdb --n_epochs=100
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    import t3nsor as t3
  File "../t3nsor/__init__.py", line 7, in <module>
    from t3nsor.decompositions import to_tt_tensor
  File "../t3nsor/decompositions.py", line 5, in <module>
    from t3nsor.utils import svd_fix
ImportError: cannot import name 'svd_fix'

**Comment by KhrulkovV** [comment]
Thanks, fixed
